# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Create configuration directory
  file:
    state: directory
    path: "{{ cobbler_configuration_directory }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: Create data directory
  file:
    state: directory
    path: "{{ cobbler_data_directory }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: Create image directory
  file:
    state: directory
    path: "{{ cobbler_image_directory }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: Create www directory
  file:
    state: directory
    path: "{{ cobbler_www_directory }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  become: true

- name: Copy configuration templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ cobbler_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
  with_items:
    - 000-default.conf
    - dhcp.template
    - isc-dhcp-server
    - ports.conf
    - settings
    - tftpd.template
  become: false

# https://unix.stackexchange.com/questions/45964/scripting-htdigest-c-path-to-file-user-user-password-in-bash
- name: Generate htdigest
  shell: "echo -n '{{ cobbler_username }}:Cobbler:' && echo -n '{{ cobbler_username }}:Cobbler:{{ cobbler_password }}' | md5sum | awk '{ print $1 }'"
  register: htdigest
  no_log: true

- name: Create htdigest file
  copy:
    content: "{{ htdigest.stdout }}\n"
    dest: "{{ cobbler_configuration_directory }}/users.digest"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"

- name: Copy cobbler wrapper script
  template:
    src: cobbler.j2
    dest: /usr/local/bin/cobbler
    mode: 0755
    owner: root
    group: root
  become: true
