# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Pull docker image
  docker_image:
    name: "{{ cobbler_docker_image }}"

- name: Prepare volume list
  set_fact:
    cobbler_volumes:
      - "{{ cobbler_image_directory }}:/mnt"
      - "{{ cobbler_data_directory }}:/var/lib/cobbler"
      - "{{ cobbler_www_directory }}:/srv/www/cobbler"
      - "{{ cobbler_configuration_directory }}/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro"
      - "{{ cobbler_configuration_directory }}/dhcp.template:/etc/cobbler/dhcp.template:ro"
      - "{{ cobbler_configuration_directory }}/isc-dhcp-server:/etc/default/isc-dhcp-server:ro"
      - "{{ cobbler_configuration_directory }}/ports.conf:/etc/apache2/ports.conf:ro"
      - "{{ cobbler_configuration_directory }}/settings:/etc/cobbler/settings:ro"
      - "{{ cobbler_configuration_directory }}/tftpd.template:/etc/cobbler/tftpd.template:ro"
      - "{{ cobbler_configuration_directory }}/users.digest:/etc/cobbler/users.digest:ro"

- name: Start container
  docker_container:
    name: "{{ cobbler_docker_container_name }}"
    image: "{{ cobbler_docker_image }}"
    state: started
    recreate: yes
    restart_policy: always
    volumes: "{{ cobbler_volumes }}"
    network_mode: host

- name: Copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  become: true
  with_items:
    - osism-cobbler
