---
- name: check if ufw is installed
  become: yes
  command: which ufw
  register: ufw
  changed_when: false
  ignore_errors: true

- name: allow tftp through ufw
  become: yes
  ufw: rule=allow port=69 proto=tcp
  when: ufw|success

- name: allow http through ufw
  become: yes
  ufw: rule=allow port=80 proto=tcp
  when: ufw|success
