---
- name: Copy auto-installation profile
  copy:
    src: "{{ cobbler_files_directory }}/{{ profile.kickstart }}"
    dest: "{{ cobbler_data_directory }}/kickstarts/{{ profile.kickstart }}"
  become: true

- name: Add profile {{ profile.name }}
  cobbler:
    username: "{{ cobbler_username }}"
    password: "{{ cobbler_password }}"
    server_url: "{{ cobbler_server_url }}"
    entity: profile
    action: add
    params:
      name: "{{ profile.name }}"
      distro: "{{ profile.distro }}"
      kickstart: "/var/lib/cobbler/kickstarts/{{ profile.kickstart }}"
