---
- name: Check if distribution {{ distro.name }} exists
  cobbler:
    username: "{{ cobbler_username }}"
    password: "{{ cobbler_password }}"
    server_url: "{{ cobbler_server_url }}"
    entity: distro
    action: has
    params:
      name: "{{ distro.name }}-{{ distro.arch }}"
  register: distribution_check

- name: Download iso image for distribution {{ distro.name }}
  get_url:
    url: "{{ distro.url }}"
    dest: "{{ cobbler_image_directory }}/{{ distro.name }}.iso"
  when: not distribution_check.exists
  async: "{{ cobbler_fetch_image_timeout }}"
  poll: 2

- name: Mount iso image for distribution {{ distro.name }}
  mount:
    name: "{{ cobbler_image_directory }}/{{ distro.name }}"
    src: "{{ cobbler_image_directory }}/{{ distro.name }}.iso"
    state: mounted
    fstype: iso9660
    opts: "loop,ro"
  become: true
  when: not distribution_check.exists

# NOTE: Mounted files only visible after a restart of the container

- include: task-restart.yml
  when: not distribution_check.exists

- include: wait-for-service.yml
  when: not distribution_check.exists

- name: Import files from iso image for distribution {{ distro.name }}
  cobbler:
    server_url: "http://{{ cobbler_host }}:{{ cobbler_port }}/cobbler_api"
    username: "{{ cobbler_username }}"
    password: "{{ cobbler_password }}"
    action: import
    params:
      name: "{{ distro.name }}"
      arch: "{{ distro.arch }}"
      path: "/mnt/{{ distro.name }}"
  when: not distribution_check.exists

- name: Unmount iso image for distribution {{ distro.name }}
  mount:
    name: "{{ cobbler_image_directory }}/{{ distro.name }}"
    state: unmounted
  become: true
  when: not distribution_check.exists
