---
- name: Add repository
  cobbler:
    username: "{{ cobbler_username }}"
    password: "{{ cobbler_password }}"
    server_url: "{{ cobbler_server_url }}"
    entity: repo
    action: add
    params: "{{ repository }}"
