---
- name: Install python2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python2
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for preparations
  hosts: all
  tags: [ prepare ]

  vars:
    operator_user: vagrant
    operator_group: vagrant
    operator_user_id: 1000
    operator_group_id: 1000
    docker_user: vagrant

  roles:
  - role: osism.operator
  - role: osism.docker

- name: Playbook for role testing
  hosts: all
  tags: [ cobbler ]
  connection: paramiko

  vars:
    cobbler_files_directory: ../files
    cobbler_dhcp_interface: docker0
    cobbler_dhcp_nameserver: 172.17.0.1
    cobbler_dhcp_netmask: 255.255.255.0
    cobbler_dhcp_router: 172.17.0.1
    cobbler_dhcp_subnet: 172.17.0.0
    operator_user: vagrant
    operator_group: vagrant

  roles:
  - role: ../../ansible-cobbler
