---
- name: Install python2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python2
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for preparations
  hosts: all

  roles:
  - role: osism.operator
  - role: osism.docker

- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    cobbler_dhcp_interface: enp0s3
    cobbler_dhcp_nameserver: 10.0.2.3
    cobbler_dhcp_netmask: 255.255.255.0
    cobbler_dhcp_router: 10.0.2.3
    cobbler_dhcp_subnet: 10.0.2.0

  roles:
  - role: ../../ansible-cobbler
